hidden_dim: 128
n_heads: 8
n_layers: 1
lr: 3e-3
weight_decay: 1e-4
batch_size: 16
n_epochs: 100
early_stopping_patience: 2
early_stopping_start_epoch: 50
dropout: 0.3
cells_per_crop: 500
crops_per_patient_train: 20
crops_per_patient_test: 50
mixup_n_pseudo: 300
mixup_alpha: 0.5
mixup_noise_var: 1e-5
lr_warmup_epochs: 10
preprocess: raw
